app/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from users.views import UserModelViewSet

router = DefaultRouter()
router.register('users', UserModelViewSet)

urlpatterns = [
    path('', include('djangofront.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/djangofront/urls.py
from django.urls import path, include

from djangofront.views import (
    index, verification, LoginView, RegisterView, PasswordChangeView, LogoutView, ProfileView,
    CompanyList, CompanyCreate, CompanyUpdate, CompanyDetail, CompanyDelete,
    CaseList, CaseCreate, CaseDetail, CaseUpdate, CaseDelete,
    UserCaseList, UserCompanyList,
    update_case_with_ajax, search_elems_with_ajax
)

app_name = 'djangofront'

urlpatterns = [

    # users/login/ [name='login']
    # users/logout/ [name='logout']
    # users/password_change/ [name='password_change']
    # users/password_change/done/ [name='password_change_done']
    # users/password_reset/ [name='password_reset']
    # users/password_reset/done/ [name='password_reset_done']
    # users/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # users/reset/done/ [name='password_reset_complete']
    # path('djangofront/profile/', include('django.contrib.auth.urls')),

    path('', index, name='index'),
    path('djangofront/verification/', verification, name='verification'),
    path('djangofront/search_elems_with_ajax/', search_elems_with_ajax, name='search_elems_with_ajax'),

    path('djangofront/register/', RegisterView.as_view(), name='register'),
    path('djangofront/login/', LoginView.as_view(), name='login'),
    path('djangofront/logout/', LogoutView.as_view(), name='logout'),
    path('djangofront/profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('djangofront/profile/password_change/', PasswordChangeView.as_view(), name='password_change'),

    path('djangofront/companies/', CompanyList.as_view(), name='company_list'),
    path('djangofront/companies/create/', CompanyCreate.as_view(), name='company_create'),
    path('djangofront/companies/update/<int:pk>/', CompanyUpdate.as_view(), name='company_update'),
    path('djangofront/companies/detail/<int:pk>/', CompanyDetail.as_view(), name='company_detail'),
    path('djangofront/companies/delete/<int:pk>/', CompanyDelete.as_view(), name='company_delete'),

    path('djangofront/cases/', CaseList.as_view(), name='case_list'),
    path('djangofront/cases/create/', CaseCreate.as_view(), name='case_create'),
    path('djangofront/cases/update/<int:pk>/', CaseUpdate.as_view(), name='case_update'),
    path('djangofront/cases/detail/<int:pk>/', CaseDetail.as_view(), name='case_detail'),
    path('djangofront/cases/delete/<int:pk>/', CaseDelete.as_view(), name='case_delete'),

    path('djangofront/cases/update_case_with_ajax/<int:pk>/', update_case_with_ajax, name='update_case_with_ajax'),

    path('djangofront/usercompanies/', UserCompanyList.as_view(), name='user_company_list'),
    path('djangofront/usercases/', UserCaseList.as_view(), name='user_case_list'),
]

app/djangofront/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as Login, LogoutView as Logout, PasswordChangeView as PasswordChange
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.views.generic.edit import BaseDeleteView

from companies.models import Company, Case, Comment
from content.models import Tag
from djangofront.forms import (UserLoginForm, UserRegisterForm, UserProfileForm,
                               CompanyForm, CaseForm, ImageForm, TagForm, PasswordChangeForm,
                               CompanyDetailForm, CaseDetailForm,
                               CommentForm)
from djangofront.mixin import UserIsNotNoneMixin, UserIsActiveMixin, PreviousPageMixin, SessionCacheMixin


@user_passes_test(lambda u: u is not None)
def index(request):
    context = {'title': 'Main'}
    return render(request, 'index.html', context)


@user_passes_test(lambda u: u is not None and u.is_active)
def verification(request):
    context = {'title': 'Verification'}
    return render(request, 'verification.html', context)


class LoginView(PreviousPageMixin, UserIsNotNoneMixin, Login):
    form_class = UserLoginForm
    template_name = 'login.html'
    success_url = reverse_lazy('djangofront:index')
    extra_context = {'title': 'Login'}

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.success_url)


class ProfileView(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    form_class = UserProfileForm
    template_name = 'profile.html'
    success_message = 'Your profile was updated successfully!'

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:profile', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, Logout):
    next_page = reverse_lazy('djangofront:index')


class RegisterView(PreviousPageMixin, SuccessMessageMixin, CreateView):
    form_class = UserRegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('djangofront:login')
    extra_context = {'title': 'Login'}
    success_message = 'Your account was created successfully! Please verify your account by following the link we sent to your email.'

    def form_valid(self, form):
        super().form_valid(form)
        return HttpResponseRedirect(reverse_lazy('djangofront:login'))


class PasswordChangeView(PreviousPageMixin, PasswordChange):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('djangofront:index')
    template_name = 'password_change.html'


class CompanyList(PreviousPageMixin, LoginRequiredMixin, ListView):
    model = Company
    extra_context = {'title': 'blackemployer companies list'}
    ordering = ['title']

    def get_queryset(self):
        return Company.objects.filter(is_active=True)


class UserCompanyList(PreviousPageMixin, LoginRequiredMixin, ListView):
    model = Company
    template_name = 'companies/company_list_user.html'
    extra_context = {'title': 'blackemployer my companies list'}
    ordering = ['title']

    def get_queryset(self):
        return Company.objects.filter(creator=self.request.user, is_active=True)


class CompanyCreate(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'companies/company_form.html'
    success_message = 'Success! New company is created!'
    extra_context = {
        'title': 'blackemployer - company create'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CompanyDetail(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, UpdateView):
    model = Company
    template_name = 'companies/company_detail.html'
    form_class = CompanyDetailForm
    extra_context = {
        'title': 'blackemployer - company detail',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({'sub_object_list': Case.objects.filter(company=self.object)})
        return super().get(request, *args, **kwargs)


class CompanyUpdate(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Company
    template_name = 'companies/company_form.html'
    form_class = CompanyForm
    extra_context = {
        'title': 'blackemployer - company update',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({'sub_object_list': self.object.case_set.all()})
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CompanyDelete(BaseDeleteView):
    model = Company

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.success_url = reverse_lazy('djangofront:company_list')
        return HttpResponseRedirect(self.success_url)


class CaseList(LoginRequiredMixin, ListView):
    pass


class CaseCreate(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Case
    form_class = CaseForm
    template_name = 'companies/case_form.html'
    success_message = 'Success! New case is created!'
    extra_context = {
        'title': 'blackemployer - case create',
        'image_form': ImageForm(),
        'tag_form': TagForm(),
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.company = Company.objects.get(id=self.request.session.get('company_id'))
        self.object.creator = self.request.user
        self.success_url = reverse_lazy('djangofront:case_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CaseDetail(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, UpdateView):
    model = Case
    template_name = 'companies/case_detail.html'
    form_class = CaseDetailForm
    extra_context = {
        'title': 'blackemployer - case detail',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({
            'comment_list': self.object.comment_set.all().filter(is_active=True).order_by('created_at'),
            'tags_list': self.object.tags.all(),
            'comment_form': CommentForm(),
        })
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.POST.get('text'):
            Comment.objects.create(case=self.object, creator=request.user, text=request.POST.get('text'))
        return HttpResponseRedirect(reverse_lazy('djangofront:case_detail', kwargs={'pk': self.object.pk}))


class CaseUpdate(SessionCacheMixin, PreviousPageMixin, UpdateView):
    model = Case
    form_class = CaseForm
    extra_context = {
        'title': 'blackemployer - case',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({
            'comment_list': self.object.comment_set.all(),
            'tags_list': self.object.tags.all(),
            'image_form': ImageForm(),
            'tag_form': TagForm(),
        })
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:case_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CaseDelete(BaseDeleteView):
    model = Case

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.company.pk})
        return HttpResponseRedirect(self.success_url)


class UserCaseList(UserIsActiveMixin, LoginRequiredMixin, ListView):
    model = Case
    extra_context = {'title': 'My Case List'}
    ordering = ['updated_at']

    def get_queryset(self):
        return Case.objects.filter(creator=self.request.user, is_active=True)


def update_case_with_ajax(request, pk):
    case = Case.objects.get(pk=pk)

    delete_tag_pk = request.GET.get('delete_tag_pk')
    if delete_tag_pk:
        tag_pk = int(delete_tag_pk)
        tag = Tag.objects.get(pk=tag_pk)
        case_tags = case.tags.filter(case_tags__tags__in=tag)
        case_tags.delete()

    add_tag_title = request.POST.get('add_tag_title')
    if add_tag_title:
        tag_title = add_tag_title
        tag, is_created = Tag.objects.get_or_create(title=tag_title)
        case.tags.add(tag)

    context = {
        'tags_list': case.tags.all(),
    }
    tags_html = render_to_string('companies/includes/tags.html', context, request)

    return JsonResponse({
        'tags_html': tags_html,
    })


def search_elems_with_ajax(request):
    search_str = request.GET.get('search_str')
    companies_list = []
    cases_list = []
    if search_str:
        companies_list = Company.objects.filter(

app/djangofront/templates/companies/case_detail.html
{% extends 'base.html' %}

{% block content %}

    {#    header #}
    <div class="header">
        <div class="back-btn-box">
            <a class="back-btn-small" href="{{ previous_page_url }}"></a>
        </div>
        <div class="header-text">
            <h1 class="display-5 fw-bold">Case</h1>
            <p>{{ object }}</p>
        </div>
    </div>

    {#  form #}
    <form>
        <div class="form-group">

            <label class="form-label mt-4" for="{{ form.case_date.auto_id }}">{{ form.case_date.label }}</label>
            {{ form.case_date }}

            <label class="form-label mt-4" for="{{ form.case_description.auto_id }}">{{ form.case_description.label }}</label>
            {{ form.case_description }}

            <label class="form-label mt-4" for="{{ form.position.auto_id }}">{{ form.position.label }}</label>
            {{ form.position }}

            <label class="form-label mt-4" for="{{ form.position_description.auto_id }}">{{ form.position_description.label }}</label>
            {{ form.position_description }}

        </div>
    </form>

    {# image box#}
    <div class="image-box">
        {% if object.image %}
            <img class="image" src="{{ object.image.url }}" alt="ooops">
        {% endif %}
    </div>

    <!-- tags -->
    {% if object_tag_list %}
        <p class="display-6 header-text fw-bold"> Tags:</p>
        <div class="list-group">
            {% for obj in object_tag_list %}
                <div class="btn-group">
                    <a href="{% url 'djangofront:case_update' obj.pk %}" class="list-group-item">{{ obj }}</a>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {#    comments#}
    {% if comment_list %}
        <p class="display-6 header-text fw-bold"> Comments:</p>
        <div class="list-group">
            {% for obj in comment_list %}
                {% if obj.creator == user %}
                    {% include 'companies/includes/comment_user.html' %}
                {% else %}
                    {% include 'companies/includes/comment_other.html' %}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    <p class="display-6 header-text fw-bold mt-5"> Add comment:</p>
    {#  comment form #}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">

            <label class="form-label mt-4" for="{{ comment_form.text.auto_id }}">{{ comment_form.text.label }}</label>
            {{ comment_form.text }}

            <label class="form-label mt-4" for="{{ comment_form.image.auto_id }}">{{ comment_form.image.label }}</label>
            {{ comment_form.image }}

            <div class="text-center mt-4">
                <input class="btn btn-primary" type="submit" value="Add Comment">
            </div>
        </div>
    </form>

    {% include 'includes/inn_delete_modal.html' %}

{% endblock %}

app/djangofront/templates/companies/case_form.html
{% extends 'base.html' %}

{% block content %}

    {#    header #}
    <div class="header">
    <div class="back-btn-box">
        <a class="back-btn-small" href="{{ previous_page_url }}"></a>
    </div>
    <div class="header-text">
        <h1 class="display-5 fw-bold">Case</h1>
        <p>{{ object }}</p>
    </div>
</div>

    {#  form #}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">

            <label class="form-label mt-4" for="{{ form.case_date.auto_id }}">{{ form.case_date.label }}</label>
            {{ form.case_date }}

            <label class="form-label mt-4" for="{{ form.case_description.auto_id }}">{{ form.case_description.label }}</label>
            {{ form.case_description }}

            <label class="form-label mt-4" for="{{ form.position.auto_id }}">{{ form.position.label }}</label>
            {{ form.position }}

            <label class="form-label mt-4" for="{{ form.position_description.auto_id }}">{{ form.position_description.label }}</label>
            {{ form.position_description }}

            <div class="text-center mt-4">
                <input class="btn btn-primary" type="submit" value="Ok">
            </div>
        </div>
    </form>


    {# image box#}
    <div class="image-box">
        {% if object.image %}
            <img class="image" src="{{ object.image.url }}" alt="ooops">
        {% else %}
            <img class="image" src="{{ STATIC_PREFIX }}media/images/no_image.png" alt="ooops">
        {% endif %}
    </div>

    {#  image_form #}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label class="form-label mt-4" for="{{ image_form.image.auto_id }}">{{ image_form.image.label }}</label>
        {{ image_form.image }}
        <div class="text-center mt-4">
            <input class="btn btn-primary" type="submit" value="Add image">
        </div>
    </form>



    {% if object %}
    <!-- tags -->
        <div class="tags">
            {% include 'companies/includes/tags.html' %}
        </div>
    <!-- tag form -->
    <form method="post">
        {% csrf_token %}
        <div class="form-group">

            <label class="form-label mt-4" for="{{ tag_form.tag_title.auto_id }}">{{ tag_form.tag_title.label }}</label>
            {{ tag_form.tag_title }}

            <div class="text-center mt-4">
                <input class="btn btn-primary" type="submit" value="Add tag">
            </div>
        </div>
    </form>
    {% endif %}

    {% include 'includes/inn_delete_modal.html' %}
    <script src="{{ STATIC_PREFIX }}js/delete_tag.js" defer></script>

{% endblock %}

app/djangofront/templates/companies/company_detail.html
{% extends 'base.html' %}

{% block content %}

    {#    header #}
    <div class="header">
        <div class="back-btn-box">
            <a class="back-btn-small" href="{{ previous_page_url }}"></a>
        </div>
        <div class="header-text">
            <h1 class="display-5 fw-bold">Company</h1>
            <p>{{ object }}</p>
        </div>
    </div>

    {# image box#}
    {% if object.image %}
        <div class="image-box">
            <img class="image" src="{{ object.image.url }}" alt="ooops">
        </div>
    {% endif %}

    {#  form #}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">

            <label class="form-label mt-4" for="{{ form.title.auto_id }}">{{ form.title.label }}</label>
            {{ form.title }}

            <label class="form-label mt-4" for="{{ form.website.auto_id }}">{{ form.website.label }}</label>
            {{ form.website }}

            <label class="form-label mt-4" for="{{ form.text.auto_id }}">{{ form.text.label }}</label>
            {{ form.text }}
        </div>
    </form>

    <!-- cases -->
    <p class="display-6 header-text fw-bold mt-5"> Cases:</p>
    <div class="list-group text-center">
        {% if sub_object_list %}
            {% for obj in sub_object_list %}
                <div class="btn-group">
                    <a href="{% url 'djangofront:case_detail' obj.pk %}"
                       class="list-group-item list-group-item-action">{{ obj }}</a>
                </div>
            {% endfor %}
        {% else %}
            <p class="text-center">No cases yet</p>
        {% endif %}
    </div>


    <!-- add case -->
    <div class="d-grid">
        <a class="btn btn_add" href="{% url 'djangofront:case_create' %}" id="add"></a>
    </div>

{% endblock %}

app/djangofront/templates/companies/company_form.html
{% extends 'base.html' %}

{% block content %}

    {#    header #}
    <div class="header">
        <div class="back-btn-box">
            <a class="back-btn-small" href="{{ previous_page_url }}"></a>
        </div>
        <div class="header-text">
            <h1 class="display-5 fw-bold">Company</h1>
            <p>{{ object }}</p>
        </div>
    </div>

    {# image box#}
    <div class="image-box">
        {% if object.image %}
            <img class="image" src="{{ object.image.url }}" alt="ooops">
        {% else %}
            <img class="image" src="{{ STATIC_PREFIX }}media/images/no_image.png" alt="ooops">
        {% endif %}
    </div>

    {#  form #}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">

            <label class="form-label mt-4" for="{{ form.image.auto_id }}">{{ form.image.label }}</label>
            {{ form.image }}

            <label class="form-label mt-4" for="{{ form.title.auto_id }}">{{ form.title.label }}</label>
            {{ form.title }}

            <label class="form-label mt-4" for="{{ form.website.auto_id }}">{{ form.website.label }}</label>
            {{ form.website }}

            <label class="form-label mt-4" for="{{ form.text.auto_id }}">{{ form.text.label }}</label>
            {{ form.text }}
            <div class="text-center mt-4">
                <input class="btn btn-primary" type="submit" value="Ok">
            </div>
        </div>
    </form>

    <!-- cases -->
    <p class="display-6 header-text fw-bold"> Cases:</p>
    <div class="list-group text-center">
        {% if sub_object_list %}
            {% for obj in sub_object_list %}
                <div class="btn-group">
                    <a href="{% url 'djangofront:case_update' obj.pk %}"
                       class="list-group-item list-group-item-action">{{ obj }}</a>
                </div>
            {% endfor %}
        {% else %}
            <p class="text-center">No cases yet</p>
        {% endif %}
    </div>

    {% if object %}
    <p class="display-6 header-text fw-bold"> Add Case:</p>
        <!-- add case -->
        <div class="d-grid">
            <a class="btn btn_add" href="{% url 'djangofront:case_create' %}" id="add"></a>
        </div>
    {% endif %}

{% endblock %}

app/djangofront/templates/companies/company_list.html
{% extends 'base.html' %}

{% block content %}

    <p class="display-6 text-center">Check in companies:</p>

    <!-- Search -->
    <form class="d-flex nav-item my-lg-0 mb-4" method="GET">
        <input class="form-control me-2" type="search" placeholder="Search" name="search_key">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>

    <!-- Add new object button -->
    <p class="display-6 mt-5 text-center">Or add if you havnt found:</p>
    <div class="d-grid">
        <a class="btn btn_add" href="{% url 'djangofront:company_create' %}" id="add"></a>
    </div>



    <!-- companies -->
    <p class="display-6 text-center">Companies:</p>
    <div class="companies">
    </div>

{% endblock %}

app/djangofront/templates/companies/company_list_user.html
{% extends 'base.html' %}

{% block content %}

    {#    header #}
    <div class="header">
        <div class="back-btn-box">
            <a class="back-btn-small" href="{{ previous_page_url }}"></a>
        </div>
        <div class="header-text">
            <h1 class="display-5 fw-bold">My Companies:</h1>
            <p>{{ object }}</p>
        </div>
    </div>

    {#    user_companies #}
    <div class="companies">
        {% include 'companies/includes/user_companies.html' %}
    </div>

    <!-- Add new object button -->
    <p class="display-6 mt-5 text-center"></p>
    <div class="d-grid">
        <a class="btn btn_add" href="{% url 'djangofront:company_create' %}" id="add"></a>
    </div>




{% endblock %}