app/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from users.views import UserModelViewSet

router = DefaultRouter()
router.register('users', UserModelViewSet)

urlpatterns = [
    path('', include('djangofront.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/djangofront/urls.py
from django.urls import path, include

from djangofront.views import (
    index, verification, LoginView, RegisterView, PasswordChangeView, LogoutView, ProfileView,
    CompanyList, CompanyCreate, CompanyUpdate, CompanyDetail, CompanyDelete,
    CaseList, CaseCreate, CaseDetail, CaseUpdate, CaseDelete,
    UserCaseList, UserCompanyList,
    update_case_with_ajax, search_elems_with_ajax
)

app_name = 'djangofront'

urlpatterns = [

    # users/login/ [name='login']
    # users/logout/ [name='logout']
    # users/password_change/ [name='password_change']
    # users/password_change/done/ [name='password_change_done']
    # users/password_reset/ [name='password_reset']
    # users/password_reset/done/ [name='password_reset_done']
    # users/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # users/reset/done/ [name='password_reset_complete']
    # path('djangofront/profile/', include('django.contrib.auth.urls')),

    path('', index, name='index'),
    path('djangofront/verification/', verification, name='verification'),
    path('djangofront/search_elems_with_ajax/', search_elems_with_ajax, name='search_elems_with_ajax'),

    path('djangofront/register/', RegisterView.as_view(), name='register'),
    path('djangofront/login/', LoginView.as_view(), name='login'),
    path('djangofront/logout/', LogoutView.as_view(), name='logout'),
    path('djangofront/profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('djangofront/profile/password_change/', PasswordChangeView.as_view(), name='password_change'),

    path('djangofront/companies/', CompanyList.as_view(), name='company_list'),
    path('djangofront/companies/create/', CompanyCreate.as_view(), name='company_create'),
    path('djangofront/companies/update/<int:pk>/', CompanyUpdate.as_view(), name='company_update'),
    path('djangofront/companies/detail/<int:pk>/', CompanyDetail.as_view(), name='company_detail'),
    path('djangofront/companies/delete/<int:pk>/', CompanyDelete.as_view(), name='company_delete'),

    path('djangofront/cases/', CaseList.as_view(), name='case_list'),
    path('djangofront/cases/create/', CaseCreate.as_view(), name='case_create'),
    path('djangofront/cases/update/<int:pk>/', CaseUpdate.as_view(), name='case_update'),
    path('djangofront/cases/detail/<int:pk>/', CaseDetail.as_view(), name='case_detail'),
    path('djangofront/cases/delete/<int:pk>/', CaseDelete.as_view(), name='case_delete'),

    path('djangofront/cases/update_case_with_ajax/<int:pk>/', update_case_with_ajax, name='update_case_with_ajax'),

    path('djangofront/usercompanies/', UserCompanyList.as_view(), name='user_company_list'),
    path('djangofront/usercases/', UserCaseList.as_view(), name='user_case_list'),
]

app/djangofront/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as Login, LogoutView as Logout, PasswordChangeView as PasswordChange
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.views.generic.edit import BaseDeleteView

from companies.models import Company, Case, Comment
from content.models import Tag
from djangofront.forms import (UserLoginForm, UserRegisterForm, UserProfileForm,
                               CompanyForm, CaseForm, ImageForm, TagForm, PasswordChangeForm,
                               CompanyDetailForm, CaseDetailForm,
                               CommentForm)
from djangofront.mixin import UserIsNotNoneMixin, UserIsActiveMixin, PreviousPageMixin, SessionCacheMixin


@user_passes_test(lambda u: u is not None)
def index(request):
    context = {'title': 'Main'}
    return render(request, 'index.html', context)


@user_passes_test(lambda u: u is not None and u.is_active)
def verification(request):
    context = {'title': 'Verification'}
    return render(request, 'verification.html', context)


class LoginView(PreviousPageMixin, UserIsNotNoneMixin, Login):
    form_class = UserLoginForm
    template_name = 'login.html'
    success_url = reverse_lazy('djangofront:index')
    extra_context = {'title': 'Login'}

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.success_url)


class ProfileView(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    form_class = UserProfileForm
    template_name = 'profile.html'
    success_message = 'Your profile was updated successfully!'

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:profile', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, Logout):
    next_page = reverse_lazy('djangofront:index')


class RegisterView(PreviousPageMixin, SuccessMessageMixin, CreateView):
    form_class = UserRegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('djangofront:login')
    extra_context = {'title': 'Login'}
    success_message = 'Your account was created successfully! Please verify your account by following the link we sent to your email.'

    def form_valid(self, form):
        super().form_valid(form)
        return HttpResponseRedirect(reverse_lazy('djangofront:login'))


class PasswordChangeView(PreviousPageMixin, PasswordChange):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('djangofront:index')
    template_name = 'password_change.html'


class CompanyList(PreviousPageMixin, LoginRequiredMixin, ListView):
    model = Company
    extra_context = {'title': 'blackemployer companies list'}
    ordering = ['title']

    def get_queryset(self):
        return Company.objects.filter(is_active=True)


class UserCompanyList(PreviousPageMixin, LoginRequiredMixin, ListView):
    model = Company
    template_name = 'companies/company_list_user.html'
    extra_context = {'title': 'blackemployer my companies list'}
    ordering = ['title']

    def get_queryset(self):
        return Company.objects.filter(creator=self.request.user, is_active=True)


class CompanyCreate(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'companies/company_form.html'
    success_message = 'Success! New company is created!'
    extra_context = {
        'title': 'blackemployer - company create'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CompanyDetail(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, UpdateView):
    model = Company
    template_name = 'companies/company_detail.html'
    form_class = CompanyDetailForm
    extra_context = {
        'title': 'blackemployer - company detail',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({'sub_object_list': Case.objects.filter(company=self.object)})
        return super().get(request, *args, **kwargs)


class CompanyUpdate(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Company
    template_name = 'companies/company_form.html'
    form_class = CompanyForm
    extra_context = {
        'title': 'blackemployer - company update',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({'sub_object_list': self.object.case_set.all()})
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CompanyDelete(BaseDeleteView):
    model = Company

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.success_url = reverse_lazy('djangofront:company_list')
        return HttpResponseRedirect(self.success_url)


class CaseList(LoginRequiredMixin, ListView):
    pass


class CaseCreate(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Case
    form_class = CaseForm
    template_name = 'companies/case_form.html'
    success_message = 'Success! New case is created!'
    extra_context = {
        'title': 'blackemployer - case create',
        'image_form': ImageForm(),
        'tag_form': TagForm(),
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.company = Company.objects.get(id=self.request.session.get('company_id'))
        self.object.creator = self.request.user
        self.success_url = reverse_lazy('djangofront:case_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CaseDetail(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, UpdateView):
    model = Case
    template_name = 'companies/case_detail.html'
    form_class = CaseDetailForm
    extra_context = {
        'title': 'blackemployer - case detail',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({
            'comment_list': self.object.comment_set.all().filter(is_active=True).order_by('created_at'),
            'tags_list': self.object.tags.all(),
            'comment_form': CommentForm(),
        })
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.POST.get('text'):
            Comment.objects.create(case=self.object, creator=request.user, text=request.POST.get('text'))
        return HttpResponseRedirect(reverse_lazy('djangofront:case_detail', kwargs={'pk': self.object.pk}))


class CaseUpdate(SessionCacheMixin, PreviousPageMixin, UpdateView):
    model = Case
    form_class = CaseForm
    extra_context = {
        'title': 'blackemployer - case',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({
            'comment_list': self.object.comment_set.all(),
            'tags_list': self.object.tags.all(),
            'image_form': ImageForm(),
            'tag_form': TagForm(),
        })
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:case_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CaseDelete(BaseDeleteView):
    model = Case

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.company.pk})
        return HttpResponseRedirect(self.success_url)


class UserCaseList(UserIsActiveMixin, LoginRequiredMixin, ListView):
    model = Case
    extra_context = {'title': 'My Case List'}
    ordering = ['updated_at']

    def get_queryset(self):
        return Case.objects.filter(creator=self.request.user, is_active=True)


def update_case_with_ajax(request, pk):
    case = Case.objects.get(pk=pk)

    delete_tag_pk = request.GET.get('delete_tag_pk')
    if delete_tag_pk:
        tag_pk = int(delete_tag_pk)
        tag = Tag.objects.get(pk=tag_pk)
        case_tags = case.tags.filter(case_tags__tags__in=tag)
        case_tags.delete()

    add_tag_title = request.POST.get('add_tag_title')
    if add_tag_title:
        tag_title = add_tag_title
        tag, is_created = Tag.objects.get_or_create(title=tag_title)
        case.tags.add(tag)

    context = {
        'tags_list': case.tags.all(),
    }
    tags_html = render_to_string('companies/includes/tags.html', context, request)

    return JsonResponse({
        'tags_html': tags_html,
    })


def search_elems_with_ajax(request):
    search_str = request.GET.get('search_str')
    companies_list = []
    cases_list = []
    if search_str:
        companies_list = Company.objects.filter(

app/djangofront/templates/companies/includes/cases.html
<div class="list-group text-center">
    {% if sub_object_list %}
        {% for obj in sub_object_list %}
            <div class="btn-group">
                <a href="{% url 'djangofront:case_update' obj.pk %}"
                   class="list-group-item list-group-item-action">{{ obj }}</a>
                <!-- Button trigger modal delete obj from sub_object_list -->
                <button type="button" class="btn btn_del_from_list" data-bs-toggle="modal"
                        data-bs-target="#exampleModal" data-type="cases" data-pk="{{ obj.pk }}"></button>
            </div>
        {% endfor %}
    {% else %}
        <p class="text-center">No cases yet</p>
    {% endif %}
</div>

app/djangofront/templates/companies/includes/cases_from_detail.html
<div class="list-group text-center">
    {% if sub_object_list %}
        {% for obj in sub_object_list %}
            <div class="btn-group">
                <a href="{% url 'djangofront:case_detail' obj.pk %}"
                   class="list-group-item list-group-item-action">{{ obj }}</a>
            </div>
        {% endfor %}
    {% else %}
        <p class="text-center">No cases yet</p>
    {% endif %}
</div>

app/djangofront/templates/companies/includes/comment_other.html
<div class="list-group-item">
    <p>created: {{ obj.created_at }}</p>
    <p>user: {{ obj.creator }}</p>
    <p>text: {{ obj.text }}</p>
</div>

app/djangofront/templates/companies/includes/comment_user.html
<div class="list-group-item">
    <p>created: {{ obj.created_at }}</p>
    <p>user: {{ obj.creator }}</p>
    <p>comment: {{ obj.text }}</p>
</div>

app/djangofront/templates/companies/includes/companies.html
<div class="list-group text-center">
    {% if object_list %}
        {% for obj in object_list %}
            <div class="btn-group">
                <a href="{% url 'djangofront:company_detail' obj.pk %}"
                   class="list-group-item list-group-item-action">{{ obj.title }}</a>
            </div>
        {% endfor %}
    {% else %}
        <p>No companies yet, be first to create one!</p>
    {% endif %}
</div>

app/djangofront/templates/companies/includes/search_cases.html
{% if cases_list %}
    {% for obj in cases_list %}
        <div class="btn-group">
            <a href="{% url 'djangofront:case_detail' obj.pk %}" class="list-group-item list-group-item-action">{{ obj }}</a>
        </div>
    {% endfor %}
{% endif %}

app/djangofront/templates/companies/includes/search_companies.html
{% if companies_list %}
    {% for obj in companies_list %}
        <div class="btn-group">
            <a href="{% url 'djangofront:company_detail' obj.pk %}" class="list-group-item list-group-item-action">{{ obj }}</a>
        </div>
    {% endfor %}
{% endif %}

app/djangofront/templates/companies/includes/tags.html
<p class="display-6 header-text fw-bold"> Tags:</p>
<div class="list-group">
    {% if tag_list %}
        {% for obj in tag_list %}
            <div class="btn-group">
                <a href="{% url 'djangofront:case_update' obj.pk %}"
                   class="list-group-item list-group-item-action">{{ obj }}</a>
                <!-- Button trigger modal delete obj from sub_object_list -->
                <button type="button" class="btn btn_del_from_list" data-bs-toggle="modal" data-bs-target="#exampleModal"
                        data-type="cases" data-pk="{{ obj.pk }}"></button>
            </div>
        {% endfor %}
    {% else %}
        <p class="text-center">No tags yet</p>
    {% endif %}
</div>

app/djangofront/templates/companies/includes/user_companies.html
<div class="list-group text-center">
    {% if object_list %}
        {% for obj in object_list %}
            <div class="btn-group">
                <a href="{% url 'djangofront:company_update' obj.pk %}"
                   class="list-group-item list-group-item-action">{{ obj.title }}</a>
{#                <!-- Button trigger modal delete obj from sub_object_list -->#}
{#                                    <button type="button" class="btn btn_del_from_list" data-bs-toggle="modal"#}
{#                                            data-bs-target="#exampleModal" data-type="words" data-pk="{{ obj.pk }}" data-app="elements"></button>#}
            </div>
        {% endfor %}
    {% else %}
        <p>No companies yet, create one!</p>
    {% endif %}
</div>