app/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from users.views import UserModelViewSet

router = DefaultRouter()
router.register('users', UserModelViewSet)

urlpatterns = [
    path('', include('djangofront.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/djangofront/urls.py
from django.urls import path, include

from djangofront.views import (
    index, verification, LoginView, RegisterView, PasswordChangeView, LogoutView, ProfileView,
    CompanyList, CompanyCreate, CompanyUpdate, CompanyDetail, CompanyDelete,
    CaseList, CaseCreate, CaseDetail, CaseUpdate, CaseDelete,
    UserCaseList, UserCompanyList,
    update_case_with_ajax, search_elems_with_ajax
)

app_name = 'djangofront'

urlpatterns = [

    # users/login/ [name='login']
    # users/logout/ [name='logout']
    # users/password_change/ [name='password_change']
    # users/password_change/done/ [name='password_change_done']
    # users/password_reset/ [name='password_reset']
    # users/password_reset/done/ [name='password_reset_done']
    # users/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # users/reset/done/ [name='password_reset_complete']
    # path('djangofront/profile/', include('django.contrib.auth.urls')),

    path('', index, name='index'),
    path('djangofront/verification/', verification, name='verification'),
    path('djangofront/search_elems_with_ajax/', search_elems_with_ajax, name='search_elems_with_ajax'),

    path('djangofront/register/', RegisterView.as_view(), name='register'),
    path('djangofront/login/', LoginView.as_view(), name='login'),
    path('djangofront/logout/', LogoutView.as_view(), name='logout'),
    path('djangofront/profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('djangofront/profile/password_change/', PasswordChangeView.as_view(), name='password_change'),

    path('djangofront/companies/', CompanyList.as_view(), name='company_list'),
    path('djangofront/companies/create/', CompanyCreate.as_view(), name='company_create'),
    path('djangofront/companies/update/<int:pk>/', CompanyUpdate.as_view(), name='company_update'),
    path('djangofront/companies/detail/<int:pk>/', CompanyDetail.as_view(), name='company_detail'),
    path('djangofront/companies/delete/<int:pk>/', CompanyDelete.as_view(), name='company_delete'),

    path('djangofront/cases/', CaseList.as_view(), name='case_list'),
    path('djangofront/cases/create/', CaseCreate.as_view(), name='case_create'),
    path('djangofront/cases/update/<int:pk>/', CaseUpdate.as_view(), name='case_update'),
    path('djangofront/cases/detail/<int:pk>/', CaseDetail.as_view(), name='case_detail'),
    path('djangofront/cases/delete/<int:pk>/', CaseDelete.as_view(), name='case_delete'),

    path('djangofront/cases/update_case_with_ajax/<int:pk>/', update_case_with_ajax, name='update_case_with_ajax'),

    path('djangofront/usercompanies/', UserCompanyList.as_view(), name='user_company_list'),
    path('djangofront/usercases/', UserCaseList.as_view(), name='user_case_list'),
]

app/djangofront/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as Login, LogoutView as Logout, PasswordChangeView as PasswordChange
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.views.generic.edit import BaseDeleteView

from companies.models import Company, Case, Comment
from content.models import Tag
from djangofront.forms import (UserLoginForm, UserRegisterForm, UserProfileForm,
                               CompanyForm, CaseForm, ImageForm, TagForm, PasswordChangeForm,
                               CompanyDetailForm, CaseDetailForm,
                               CommentForm)
from djangofront.mixin import UserIsNotNoneMixin, UserIsActiveMixin, PreviousPageMixin, SessionCacheMixin


@user_passes_test(lambda u: u is not None)
def index(request):
    context = {'title': 'Main'}
    return render(request, 'index.html', context)


@user_passes_test(lambda u: u is not None and u.is_active)
def verification(request):
    context = {'title': 'Verification'}
    return render(request, 'verification.html', context)


class LoginView(PreviousPageMixin, UserIsNotNoneMixin, Login):
    form_class = UserLoginForm
    template_name = 'login.html'
    success_url = reverse_lazy('djangofront:index')
    extra_context = {'title': 'Login'}

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.success_url)


class ProfileView(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    form_class = UserProfileForm
    template_name = 'profile.html'
    success_message = 'Your profile was updated successfully!'

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:profile', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, Logout):
    next_page = reverse_lazy('djangofront:index')


class RegisterView(PreviousPageMixin, SuccessMessageMixin, CreateView):
    form_class = UserRegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('djangofront:login')
    extra_context = {'title': 'Login'}
    success_message = 'Your account was created successfully! Please verify your account by following the link we sent to your email.'

    def form_valid(self, form):
        super().form_valid(form)
        return HttpResponseRedirect(reverse_lazy('djangofront:login'))


class PasswordChangeView(PreviousPageMixin, PasswordChange):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('djangofront:index')
    template_name = 'password_change.html'


class CompanyList(PreviousPageMixin, LoginRequiredMixin, ListView):
    model = Company
    extra_context = {'title': 'blackemployer companies list'}
    ordering = ['title']

    def get_queryset(self):
        return Company.objects.filter(is_active=True)


class UserCompanyList(PreviousPageMixin, LoginRequiredMixin, ListView):
    model = Company
    template_name = 'companies/company_list_user.html'
    extra_context = {'title': 'blackemployer my companies list'}
    ordering = ['title']

    def get_queryset(self):
        return Company.objects.filter(creator=self.request.user, is_active=True)


class CompanyCreate(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'companies/company_form.html'
    success_message = 'Success! New company is created!'
    extra_context = {
        'title': 'blackemployer - company create'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CompanyDetail(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, UpdateView):
    model = Company
    template_name = 'companies/company_detail.html'
    form_class = CompanyDetailForm
    extra_context = {
        'title': 'blackemployer - company detail',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({'sub_object_list': Case.objects.filter(company=self.object)})
        return super().get(request, *args, **kwargs)


class CompanyUpdate(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Company
    template_name = 'companies/company_form.html'
    form_class = CompanyForm
    extra_context = {
        'title': 'blackemployer - company update',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({'sub_object_list': self.object.case_set.all()})
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CompanyDelete(BaseDeleteView):
    model = Company

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.success_url = reverse_lazy('djangofront:company_list')
        return HttpResponseRedirect(self.success_url)


class CaseList(LoginRequiredMixin, ListView):
    pass


class CaseCreate(PreviousPageMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Case
    form_class = CaseForm
    template_name = 'companies/case_form.html'
    success_message = 'Success! New case is created!'
    extra_context = {
        'title': 'blackemployer - case create',
        'image_form': ImageForm(),
        'tag_form': TagForm(),
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.company = Company.objects.get(id=self.request.session.get('company_id'))
        self.object.creator = self.request.user
        self.success_url = reverse_lazy('djangofront:case_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CaseDetail(SessionCacheMixin, PreviousPageMixin, LoginRequiredMixin, UpdateView):
    model = Case
    template_name = 'companies/case_detail.html'
    form_class = CaseDetailForm
    extra_context = {
        'title': 'blackemployer - case detail',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({
            'comment_list': self.object.comment_set.all().filter(is_active=True).order_by('created_at'),
            'tags_list': self.object.tags.all(),
            'comment_form': CommentForm(),
        })
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.POST.get('text'):
            Comment.objects.create(case=self.object, creator=request.user, text=request.POST.get('text'))
        return HttpResponseRedirect(reverse_lazy('djangofront:case_detail', kwargs={'pk': self.object.pk}))


class CaseUpdate(SessionCacheMixin, PreviousPageMixin, UpdateView):
    model = Case
    form_class = CaseForm
    extra_context = {
        'title': 'blackemployer - case',
    }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.extra_context.update({
            'comment_list': self.object.comment_set.all(),
            'tags_list': self.object.tags.all(),
            'image_form': ImageForm(),
            'tag_form': TagForm(),
        })
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.success_url = reverse_lazy('djangofront:case_update', kwargs={'pk': self.object.pk})
        return super().form_valid(form)


class CaseDelete(BaseDeleteView):
    model = Case

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        self.success_url = reverse_lazy('djangofront:company_update', kwargs={'pk': self.object.company.pk})
        return HttpResponseRedirect(self.success_url)


class UserCaseList(UserIsActiveMixin, LoginRequiredMixin, ListView):
    model = Case
    extra_context = {'title': 'My Case List'}
    ordering = ['updated_at']

    def get_queryset(self):
        return Case.objects.filter(creator=self.request.user, is_active=True)


def update_case_with_ajax(request, pk):
    case = Case.objects.get(pk=pk)

    delete_tag_pk = request.GET.get('delete_tag_pk')
    if delete_tag_pk:
        tag_pk = int(delete_tag_pk)
        tag = Tag.objects.get(pk=tag_pk)
        case_tags = case.tags.filter(case_tags__tags__in=tag)
        case_tags.delete()

    add_tag_title = request.POST.get('add_tag_title')
    if add_tag_title:
        tag_title = add_tag_title
        tag, is_created = Tag.objects.get_or_create(title=tag_title)
        case.tags.add(tag)

    context = {
        'tags_list': case.tags.all(),
    }
    tags_html = render_to_string('companies/includes/tags.html', context, request)

    return JsonResponse({
        'tags_html': tags_html,
    })


def search_elems_with_ajax(request):
    search_str = request.GET.get('search_str')
    companies_list = []
    cases_list = []
    if search_str:
        companies_list = Company.objects.filter(

app/djangofront/templates/base.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}
        <title>{{ title|title }}</title>
    {% endblock %}

    <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/style.css">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    {% block css %}
    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position: fixed; top: 0; width: 100%">
    <div class="container">
        <a class="navbar-brand" href="{% url 'djangofront:index' %}">blackemployer.com</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangofront:company_list' %}">Companies list</a>
                </li>
                {#                <li class="nav-item dropdown">#}
                {#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"#}
                {#                       data-bs-toggle="dropdown" aria-expanded="false">#}
                {#                        Dropdown#}
                {#                    </a>#}
                {#                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
                {#                        <li><a class="dropdown-item" href="{% url '' %}">item_1</a></li>#}
                {#                        <li><a class="dropdown-item" href="{% url '' %}">item_2</a></li>#}
                {#                    </ul>#}
                {#                </li>#}
            </ul>
            {% if user.is_authenticated %}
                <div class="nav-item">
                    <a class="nav-link grey" href="{% url 'djangofront:profile' pk=user.pk %}">Profile</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link grey" href="{% url 'djangofront:logout' %}">Logout</a>
                </div>
            {% else %}
                <a class="nav-link grey" href="{% url 'djangofront:register' %}">SignUp</a>
                <a class="nav-link grey" href="{% url 'djangofront:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>


<!-- Main block -->
<main class="container bg-light rounded-3 p-5 mb-4" style="margin-top: 50px; margin-bottom: 100px ">

    <!-- Messages and Errors -->
    <div>
        {% if form.errors or messages %}

            {% if messages %}
                {% for message in messages %}

                    <div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show"
                         role="alert" style="margin-top: 50px;">
                        <p><strong>Message!</strong></p>
                        {{ message }}

                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                {% endfor %}
            {% endif %}

            {% if form.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    <p><strong>Error!</strong></p>

                    {% for field, error in form.errors.items %}

                        {% if field == '__all__' %}

                            {{ error }}

                        {% else %}

                            '{{ field }}': {{ error }}

                        {% endif %}

                    {% endfor %}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
            {% endif %}

        {% endif %}

    </div>

    <!-- Page Content -->
    <div>
        {% block content %}
        {% endblock %}
    </div>

</main>

<!-- Footer -->
<footer class="footer mt-auto bg-light" style="position: fixed; bottom: 0; width: 100%">
    <a href="https://github.com/prapeller/blackemployer_api"
       class="nav justify-content-center text-center text-muted pt-3 mb-3 text-muted text-decoration-none lh-1">
        <img src="https://github.githubassets.com/images/modules/site/icons/footer/github-mark.svg" width="20"
             height="20" loading="lazy" decoding="async" alt="GitHub mark" class="me-2">
        <span> {% now 'Y' %} © this project repository at github</span>
    </a>
</footer>


<!-- other scripts -->
<script src="{{ STATIC_PREFIX }}js/jquery/jquery.min.js"></script>
<script src="{{ STATIC_PREFIX }}js/search_elems.js"></script>
</body>

</html>

app/djangofront/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center">
        {% if user.is_authenticated %}
            <p class="display-6 text-center">search in companies and cases:</p>

            <!-- search companies and cases -->
            <form class="d-flex nav-item my-lg-0 mb-4" method="GET">
                <input id="search_elems" class="form-control me-2" type="search" placeholder="Search" name="search_key">
{#                <button class="btn btn-outline-success" type="submit">Search</button>#}
            </form>

            <div class="search_elems">
                <div class="search_companies">
                    {% include 'companies/includes/search_companies.html' %}
                </div>
                <div class="search_cases">
                    {% include 'companies/includes/search_cases.html' %}
                </div>
            </div>

            <!-- Add new object button -->
            <div class="d-grid">
                <a class="btn btn_add" href="{% url 'djangofront:company_create' %}" id="add"></a>
            </div>

        {% else %}
            <p>Please SignUp or Login to continue</p>
        {% endif %}
    </div>

{% endblock %}

app/djangofront/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="center-block">
        <div class="card shadow-lg">
            <div class="card-header">
                <h3 class="text-center my-4">Login</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'djangofront:login' %}" method="post">
                    {% csrf_token %}

                    <div class="form-group mb-2">{{ form.email }}</div>
                    <div class="form-group mb-2">{{ form.password }}</div>

                    <div class="text-center form-group mt-4">
                        <input class="btn btn-primary btn-block" type="submit" value="Ok">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small">
                    <a href="{% url 'djangofront:register' %}">Not registered yet?</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/djangofront/templates/password_change.html
{% extends 'base.html' %}

{% block content %}

        {#    header #}
    <div class="header">
        <div class="back-btn-box">
            <a class="back-btn-small" href="{{ previous_page_url }}"></a>
        </div>
        <div class="header-text">
            <h1 class="display-5 fw-bold">Change password:</h1>
            <p>{{ object }}</p>
        </div>
    </div>

    <div class="center-block">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}

                    <label class="form-label mt-4" for="{{ form.old_password.auto_id }}">{{ form.old_password.label }}</label>
                    {{ form.old_password }}
                    <label class="form-label mt-4" for="{{ form.new_password1.auto_id }}">{{ form.new_password1.label }}</label>
                    {{ form.new_password1 }}
                    <label class="form-label mt-4" for="{{ form.new_password2.auto_id }}">{{ form.new_password2.label }}</label>
                    {{ form.new_password2 }}

                    <div class="text-center form-group mt-4">
                        <input class="btn btn-primary btn-block" type="submit" value="Ok">
                    </div>
                </form>
            </div>
    </div>
{% endblock %}

app/djangofront/templates/profile.html
{% extends 'base.html' %}

{% block content %}

            {#    header #}
    <div class="header">
        <div class="back-btn-box">
            <a class="back-btn-small" href="{{ previous_page_url }}"></a>
        </div>
        <div class="header-text">
            <h1 class="display-5 fw-bold">Profile:</h1>
            <p>{{ object }}</p>
        </div>
    </div>

    <div class="center-block">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}

                    {% for field in form %}
                        <label class="form-label mt-4" for="{{ fileld.auto_id }}">{{ field.label }}</label>
                        <div class="form-group mb-2">{{ field }}</div>
                    {% endfor %}

                    <div class="text-center form-group mt-4">
                        <input class="btn btn-primary btn-block" type="submit" value="Ok">
                    </div>

                    <div class="text-center form-group mt-4">
                        <a class="btn btn-primary" href="{% url 'djangofront:password_change' %}">Change password</a>
                    </div>
                    <div class="text-center form-group mt-4">
                        <a class="btn btn-primary" href="{% url 'djangofront:user_company_list' %}">My companies</a>
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
            </div>
    </div>
{% endblock %}

app/djangofront/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="center-block">
        <div class="card shadow-lg">
            <div class="card-header">
                <h3 class="text-center my-4">SignUp</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'djangofront:register' %}" method="post">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group mb-2">{{ field }}</div>
                    {% endfor %}

                    <div class="text-center form-group mt-4">
                        <input class="btn btn-primary btn-block" type="submit" value="Ok">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small">
                    <a href="{% url 'djangofront:login' %}">Signed up already?</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/djangofront/templates/verification.html
{% extends 'base.html' %}

{% block content %}
    <div class="center-block">
        <div class="card shadow-lg">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Profile activation:</h3>
            </div>
            <div class="card-body text-center">
                {% if user.is_authenticated %}
                    <h4>Congratulations! {{ user.username }}, your email was verified.</h4>
                {% else %}
                    <h3>Please verify your email.</h3>
                {% endif %}
                <br>
                <button class="btn btn-round form-control">
                    <a href="{% url 'djangofront:index' %}" class="">OK!</a>
                </button>
            </div>
        </div>
    </div>
{% endblock %}